CREATE DATABASE OrganizationDB;
GO
USE OrganizationDB;

CREATE TABLE ORGANIZATION (
    OrgID INT IDENTITY(1,1) PRIMARY KEY,
    OrgName NVARCHAR(255) NOT NULL,
    Address NVARCHAR(255),
    Phone VARCHAR(20),
    Email VARCHAR(100),
    CreatedDate DATETIME DEFAULT GETDATE()
);

ALTER TABLE ORGANIZATION
ADD OrgName_Lower AS LOWER(OrgName);


CREATE UNIQUE INDEX UX_Organization_Name
ON ORGANIZATION (OrgName_Lower);

SELECT * FROM ORGANIZATION;


